### PR TITLE
Replace compass to Sass

### PR DESCRIPTION
**Pull request by kubosho**
## Motivation

https://github.com/Compass/compass is no longer supported.

## Solutions

Use [node-sass](https://github.com/sass/node-sass) and [gulp-sass](https://github.com/dlmanning/gulp-sass). And remove source code that depends on compass.

### CODE REVIEW

**Comment by kubosho** [comment]
@MurakamiShinyu could you review this?

**Comment by MurakamiShinyu** [comment]
@kubosho Thanks! It seems very good. 

I think the following changes is also needed:
- The `src/config.rb` file is no longer used and should be removed.
- `gem install compass` should be removed from the `.travis.yml` file.

**Comment by kubosho** [comment]
> I think the following changes is also needed:
> The src/config.rb file is no longer used and should be removed.
> gem install compass should be removed from the .travis.yml file.

I will send follow up pull request.

**Comment by MurakamiShinyu** [comment]
and remove "gulp-compass" from `package.json`?

**Comment by kubosho** [comment]
Added commit aa95cf88471ef715092fefcd6cd808cf0c1aa519

**Comment by kubosho** [comment]
@MurakamiShinyu 
Now, vivliostyle-ui is compass installation is no longer required. Can you remove description in Wiki?
https://github.com/vivliostyle/vivliostyle.js/wiki/Development#setting-up-development-environment

**Comment by MurakamiShinyu** [comment]
@kubosho Fixed the wiki. Thanks!

**Comment by MurakamiShinyu** [comment]
and I will remove `gem install compass` from 
https://github.com/vivliostyle/vivliostyle.js/blob/212926965e00bc594b421e8d107a33e2e09f4e50/build/deploy-viewer-to-gh-pages.sh#L12

**Pull request merged**
